version: '3.5'
services:
  mongo:
    image: mongo:latest
    #    restart: always
    container_name: mongodb
    volumes:
#      - /home/developer/IdeaProjects/mongo/library:/data/db
      - "./db/mongo/library:/data/db"
    networks:
      - library-mongodb
    environment:
      - MONGO_INITDB_DATABASE=library
      - MONGO_INITDB_ROOT_USERNAME=alexlibrary
      - MONGO_INITDB_ROOT_PASSWORD=alexlibrary
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - "./db/mysql/library:/var/lib/mysql"
#      - /home/developer/IdeaProjects/mysql/library:/var/lib/mysql
    networks:
      - library-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
      - MYSQL_USER=alexlibrary
      - MYSQL_PASSWORD=alexlibrary
  server:
    build: .
    container_name: internetlibrary
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - DB_PORT=3306
      - DB_NAME=library
      - DB_HOST=mysql
      - MYSQL_USER=alexlibrary
      - MYSQL_USER_PASSWORD=alexlibrary
    networks:
      - library-mysql
    depends_on:
      - mongo
      - mysql

networks:
  library-mysql:
  library-mongodb:

