version: '3.5'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
      - MYSQL_USER=brs-alexlibrary
      - MYSQL_PASSWORD=alexlibrary
  web:
    build: .
    links:
      - mysql
    container_name: BRS-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=library
      - DB_HOST=mysql
      - MYSQL_USER=alexlibrary
      - MYSQL_USER_PASSWORD=alexlibrary
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql