version: '3.5'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: "mysql"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /home/developer/IdeaProjects/mysql/library:/var/lib/mysql
    #      - "./db/mysql/library:/var/lib/mysql"
    networks:
      - library-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
      - MYSQL_USER=alexlibrary
      - MYSQL_PASSWORD=alexlibrary
  mongo:
    image: mongo:latest
    #    restart: always
    container_name: mongodb
    volumes:
      - /home/developer/IdeaProjects/mongo/library:/data/db
#      - "./db/mongo/library:/data/db"
    networks:
      - library-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=library
  server:
    build: .
    container_name: internetlibrary
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - DB_PORT=3306
      - DB_NAME=library
      - DB_HOST=mysql
      - MYSQL_USER=alexlibrary
      - MYSQL_USER_PASSWORD=alexlibrary
    networks:
      - library-mysql
    depends_on:
      - mysql
      - mongo

networks:
  library-mysql:
  library-mongodb:

